version: '3'
services:
  frontend:
    image: audio-test-frontend:1
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "yarn serve --host 0.0.0.0 --port 3000"
    ports:
      - '8080:3000'
