version: "3"
services:
    backend:
        image: michigg/web-simulataneous-recording-tool:0.1
        build: .
        volumes:
            - './results:/app/results'
        environment:
            FLASK_DEBUG: 1
            FLASK_ENV: development
            FLASK_APP: main.py
        ports:
            - '5000:5000'

    redis:
        image: redis:2
        ports:
            - 6379:6379
    frontend:
        image: michigg/web-simulataneous-recording-tool:0.1
        build:
            context: frontend
            dockerfile: Dockerfile
        command: /bin/sh -c "yarn serve --host 0.0.0.0 --port 3000"
        ports:
            - '8080:3000'
